# Generated by Django 4.1.4 on 2022-12-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_document_description_remove_document_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'File excel', 'verbose_name_plural': 'File excel'},
        ),
        migrations.AddField(
            model_name='laysheet',
            name='real_demurrage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laysheet',
            name='real_despatch',
            field=models.FloatField(default=0),
        ),
    ]
