# Generated by Django 4.1.4 on 2022-12-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_document_options_laysheet_real_demurrage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laysheet',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.document'),
        ),
    ]
