# Generated by Django 4.1.4 on 2023-01-29 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_laysheet_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='laytime',
            name='detail',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laytime',
            name='laysheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.laysheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_counted_acc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_counted_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_counted_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_from',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_isCounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_not_counted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='laytime',
            name='working_time_to',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
