# Generated by Django 4.1.4 on 2023-01-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_laytime_detail_laytime_laysheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laysheet',
            old_name='vehicle_mother',
            new_name='vehicle_trip',
        ),
    ]
