# Generated by Django 4.1.4 on 2023-01-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_laysheet_arrival_windows_laysheet_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laysheet',
            old_name='cargo_quantity',
            new_name='load',
        ),
        migrations.RenameField(
            model_name='laysheet',
            old_name='discharge_rate',
            new_name='weight',
        ),
    ]
